name: Test docs build
on:
  push:
  pull_request:

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - name: Build docs with warnings-as-errors
        run: python -m sphinx -b html -W --keep-going docs/source docs/build/html